id: PDC5A0726
initial_creation_type: input
source_metadata:
  Title: Śrīmokṣākaraguptaviracitā tarkabhāṣāṭīkā
  Editor: Bhattacharyya, Beynotosh
  Publisher: The Oriental Institute
  Place of Publication: Baroda
  Year: '1942'
  Tarkabhāṣāṭīkā:
    Text Version: Roman
    Input Personnel: DSBC Staff
    Input Date: '2013'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:53:13.111125'
last_modified_at: '2022-03-08T16:53:13.111134'
